language: node_js

node_js:
    - "4.1"
    #- "4.0"
    #- "0.12"
    #- "0.11"
    #- "0.10"



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



before_script:

    # Store all files in your own bin
    - mkdir bin
    - export PATH=$PATH:$PWD/bin/


    # Install validation tools
    - npm install -g htmlhint csslint jshint jscs jsonlint js-yaml html-minifier@0.8.0 clean-css uglify-js
    
    # Install phpcs
    #- curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
    #- install --mode 0755 phpcs.phar $PWD/bin/phpcs

    # Install phpmd
    #- wget -c http://static.phpmd.org/php/latest/phpmd.phar
    #- install --mode 0755 phpmd.phar $PWD/bin/phpmd
    
    # Download dbwebb-validate
    - wget -O dbwebb-validate https://raw.githubusercontent.com/mosbth/dbwebb-cli/master/dbwebb2-validate
    - install --mode 0755 dbwebb-validate $PWD/bin/dbwebb-validate

    # Create a build directory for output
    - mkdir build



script:
    # Check versions of validation tools
    - node --version
    - npm --version
    
    - htmlhint --version
    - csslint --version
    - jscs --version
    - jshint --version
    #- phpcs --version
    #- phpmd --version
    #- jsonlint --version
    - js-yaml --version
    #- shellcheck --version
    
    - html-minifier --version
    - cleancss --version
    - uglifyjs --version
    
    # Run validation & publish
    - dbwebb-validate --version
    - dbwebb-validate --check
    - dbwebb-validate --publish --publish-to build/ example



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/be2c512032e18da5d140

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
